### ISSUE TITLE
vsc-ember-cli commands not working 

### ISSUE THREAD

**Issue by lebbers** [felixrieseberg/vsc-ember-cli#1]
After installing this extension to Visual Studio Code on Windows 8.1 i've tried to run several Ember-cli commands but the commands seem not to be working. The output window is opened but no output (or errors) is shown. Also generating new code or a new application doesn't do anything. 

The "Setup" command is the only command that does something (creates a .vscodeignore file and jsconfig.json file).

What version of Ember-cli is supported?

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting. The extension just calls whatever version of ember cli is installed on the command line. If you open up cmd.exe and just type `ember -v`, what's the output?

**Comment by lebbers** [comment]
Ember-cli version is 1.13.8

**Comment by felixrieseberg** [comment]
Huh, interesting. And inside VS Code, running the Ember Version command doesn't show you the version?

**Comment by lebbers** [comment]
It doesn't display any version

**Comment by felixrieseberg** [comment]
Hm, weird. Thanks for bearing with me here - can you do me one more favor to help me figure out what's wrong here?

1) Open up `cmd.exe` and type `node` to start the node repl
2) Run `require('child_process').execSync('ember -v').toString();`

I'd love to hear what the output is...

**Comment by lebbers** [comment]
This is my output: 'version: 1.13.8\r\nnode: 0.12.4\r\nnpm: 2.13.4\r\nos: win32 x64\r\n'

**Comment by felixrieseberg** [comment]
Thanks - I'm super baffled. That's basically what the extension is doing. I have sadly no idea what's wrong, but I'll poke the code a bit to see if I can figure out what's going on.

**Comment by lebbers** [comment]
OK thanks, no problem.

**Comment by lebbers** [comment]
I've found that VSC contains Developer Tools window and got this error directly after starting VSC: 

``` javascript
[Plugin Host] Ember is apparently installed
workbench.main.js:1602 [Plugin Host] version: 1.13.8
node: 0.12.4
npm: 2.13.4
os: win32 x64
[Plugin Host] unhandled rejected promise Object {}(anonymous function) @ workbench.main.js:1602emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:685channel.onread @ internal/child_process.js:440
workbench.main.js:1626 SyntaxError: Unexpected token v: SyntaxError: Unexpected token v
    at Object.parse (native)
    at C:\Users\[username]\.vscode\extensions\felixrieseberg.vsc-ember-cli\out\src\ember-ops.js:108:27
    at Object.getHelp (C:\Users\[username]\.vscode\extensions\felixrieseberg.vsc-ember-cli\out\src\ember-ops.js:101:12)
    at C:\Users\[username]\.vscode\extensions\felixrieseberg.vsc-ember-cli\out\src\dumb-cache.js:15:22
    at DumbCache._preloadGenerateChoices (C:\Users\[username]\.vscode\extensions\felixrieseberg.vsc-ember-cli\out\src\dumb-cache.js:14:16)
    at DumbCache.preload (C:\Users\[username]\.vscode\extensions\felixrieseberg.vsc-ember-cli\out\src\dumb-cache.js:10:21)
    at new DumbCache (C:\Users\[username]\.vscode\extensions\felixrieseberg.vsc-ember-cli\out\src\dumb-cache.js:6:18)
    at new EmberCliManager (C:\Users\[username]\.vscode\extensions\felixrieseberg.vsc-ember-cli\out\src\ember-cli.js:9:23)
    at execute (C:\Users\[username]\.vscode\extensions\felixrieseberg.vsc-ember-cli\out\extension.js:27:24)
    at C:\Users\[username]\.vscode\extensions\felixrieseberg.vsc-ember-cli\out\extension.js:8:9e.onUnexpectedError @ workbench.main.js:1626(anonymous function) @ workbench.main.js:1626e.onUnexpectedError @ workbench.main.js:1548u @ workbench.main.js:1547e.onUnexpectedPluginHostError @ workbench.main.js:1604e.handle @ workbench.main.js:1588a @ workbench.main.js:1576h.handle @ workbench.main.js:1576(anonymous function) @ workbench.main.js:1602(anonymous function) @ workbench.main.js:1602emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:685channel.onread @ internal/child_process.js:440
```

running Ember version command returns this error: 

``` javascript
[Plugin Host] Uncaught Exception:  Error: spawn ember ENOENT(anonymous function) @ workbench.main.js:1602emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:685channel.onread @ internal/child_process.js:440
workbench.main.js:1602 [Plugin Host] Error: spawn ember ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)(anonymous function) @ workbench.main.js:1602emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:685channel.onread @ internal/child_process.js:440
workbench.main.js:1626 Error: spawn ember ENOENT: Error: spawn ember ENOENT
    at exports._errnoException (util.js:837)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178)
    at onErrorNT (internal/child_process.js:344)
    at doNTCallback2 (node.js:441)
    at process._tickCallback (node.js:355)e.onUnexpectedError @ workbench.main.js:1626(anonymous function) @ workbench.main.js:1626e.onUnexpectedError @ workbench.main.js:1548u @ workbench.main.js:1547e.onUnexpectedPluginHostError @ workbench.main.js:1604e.handle @ workbench.main.js:1588a @ workbench.main.js:1576h.handle @ workbench.main.js:1576(anonymous function) @ workbench.main.js:1602(anonymous function) @ workbench.main.js:1602emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:685channel.onread @ internal/child_process.js:440
```

Hope this helps

**Comment by t-sauer** [comment]
Just a wild guess but maybe it's because of your ember-cli version. The plugin uses the `--json` option on some calls which was just recently added to ember-cli.

**Comment by felixrieseberg** [comment]
Oh yeah, that actually seems likely. Obvious fix: We should warn if people are using an unsupported Ember Cli version.

**Comment by methodmedia** [comment]
I am having the same issue with ember cli version: 1.13.13

**Comment by felixrieseberg** [comment]
Hey everyone, I just pushed out a small patch that will always open up the output window if the environment variable VSC_EMBER_CLI_DEBUG is set.

Would you mind updating the addon, setting the variable, and trying some commands? I'd love to see what's happening on the command line level. Thanks so much in advance!

**Comment by corydeppen** [comment]
Prior to adding the variable, I updated the extension and restarted Code. When I toggle the dev tools I see the following:

```
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:67 [Plugin Host] Here is the error stack:  SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.D.n._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:19:15851)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.t [as __$__nodeRequire] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\loader.js:4:1298)
    at l (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:13:2265)
```

Trying to run the `Ember: Generate Blueprint` command at this point produces the following error:

`No handler found for the command: 'extension.generate'. Ensure there is an activation event defined, if you are an extension.`

**Comment by kellyselden** [comment]
I see the `No handler found for the command: 'extension.version'. Ensure there is an activation event defined, if you are an extension.` message too

**Comment by felixrieseberg** [comment]
Thanks, that's fixed. Try again?

**Comment by corydeppen** [comment]
I get the following after updating to v0.1.10:

```
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:67 [Plugin Host] Here is the error stack:  Error: Cannot find module 'path-exists'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.D.n._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:19:15851)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\mk6784\.vscode\extensions\felixrieseberg.vsc-ember-cli-0.1.10\out\src\file-ops.js:7:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

The same `No handler found for the command` message is still displayed when I try to run a command.

**Comment by kellyselden** [comment]
same `path-exists` issue for me

**Comment by felixrieseberg** [comment]
Hey everyone, thanks so much for helping me to work through this. We should now be there - the core of the issue was apparently that Node does not always successfully spawn Node binaries (go figure). Either way, please update and try 0.1.11 - it should fix the issue all of you in this thread were having.

**Comment by kellyselden** [comment]
We are in business now good sir! Nice work.

**Comment by corydeppen** [comment]
Works for me as well. Thanks.

**Comment by felixrieseberg** [comment]
Awesome! I'm closing this for now - thank you all very much for helping me out here :clap:
